// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrFtwnW32aWUg2GOAjt-CmD4hCEPfS10',
    appId: '1:234167986290:android:decdb0ae4c13f189bb3aeb',
    messagingSenderId: '234167986290',
    projectId: 'blooddonation-89361',
    storageBucket: 'blooddonation-89361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnYAx4z4fdTqD4ebg2auWfWapM0YwPYG8',
    appId: '1:234167986290:ios:0c143fa4a8550fffbb3aeb',
    messagingSenderId: '234167986290',
    projectId: 'blooddonation-89361',
    storageBucket: 'blooddonation-89361.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGsfQ1nJkvejyYPY8vVJsUrC2tZjtXY1w',
    appId: '1:234167986290:web:ac9cba2f78db98cfbb3aeb',
    messagingSenderId: '234167986290',
    projectId: 'blooddonation-89361',
    authDomain: 'blooddonation-89361.firebaseapp.com',
    storageBucket: 'blooddonation-89361.firebasestorage.app',
    measurementId: 'G-S48TJNC5L9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnYAx4z4fdTqD4ebg2auWfWapM0YwPYG8',
    appId: '1:234167986290:ios:0c143fa4a8550fffbb3aeb',
    messagingSenderId: '234167986290',
    projectId: 'blooddonation-89361',
    storageBucket: 'blooddonation-89361.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGsfQ1nJkvejyYPY8vVJsUrC2tZjtXY1w',
    appId: '1:234167986290:web:e6f0ad308a2089d2bb3aeb',
    messagingSenderId: '234167986290',
    projectId: 'blooddonation-89361',
    authDomain: 'blooddonation-89361.firebaseapp.com',
    storageBucket: 'blooddonation-89361.firebasestorage.app',
    measurementId: 'G-VRBTCEBVL1',
  );
}
